events {}

http {
    upstream main_api {
        server main-api:8000;
    }

    upstream notification_service {
        server notification-service:8001;
    }

    upstream analytics_service {
        server analytics-service:8002;
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://main_api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /notifications/ {
            proxy_pass http://notification_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /analytics/ {
            proxy_pass http://analytics_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
